version: "3.8"
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.7.0
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - "xpack.security.enabled=false"
      - "xpack.monitoring.templates.enabled=false"
      - "xpack.watcher.enabled=false"
      - "xpack.ml.enabled=false"
      - "http.cors.enabled=true"
      - "http.cors.allow-origin=\"*\""
      - "http.cors.allow-methods=GET,POST,PUT,DELETE,OPTIONS"
      - "http.cors.allow-headers=X-Requested-With,X-Auth-Token,Content-Type,Content-Length,Authorization"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    mem_limit: 1g
    volumes:
      # - elasticsearch_data:/usr/share/elasticsearch/data
      - ./news_dashboard_es_data:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
    networks:
      - elastic

  kibana:
    image: docker.elastic.co/kibana/kibana:8.7.0
    container_name: kibana
    environment:
      - "ELASTICSEARCH_URL=http://elasticsearch:9200"
      - "xpack.security.enabled=false"
      - "xpack.monitoring.enabled=false"
      - "xpack.watcher.enabled=false"
    ports:
      - "5601:5601"
    networks:
      - elastic

networks:
  elastic:
    driver: bridge

volumes:
  elasticsearch_data2:
